"""added data and url to assets

Revision ID: 6b4ddf19cd6e
Revises: e64386005612
Create Date: 2025-09-09 22:38:56.879691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4ddf19cd6e'
down_revision: Union[str, Sequence[str], None] = 'e64386005612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('asset_url', sa.String(), nullable=True))
    op.add_column('asset', sa.Column('asset_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'asset_content')
    op.drop_column('asset', 'asset_url')
    # ### end Alembic commands ###
