"""added chat status

Revision ID: 8e416625a526
Revises: 9a92ce0b5c2b
Create Date: 2025-09-20 15:07:17.722808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import db

# revision identifiers, used by Alembic.
revision: str = '8e416625a526'
down_revision: Union[str, Sequence[str], None] = '9a92ce0b5c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    status_enum = postgresql.ENUM('ENABLED', 'DISABLED', name='chatstatus')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('chat', sa.Column('status', status_enum, nullable=False, server_default='ENABLED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'status')
    # ### end Alembic commands ###
