"""prod v1

Revision ID: 9a92ce0b5c2b
Revises: 
Create Date: 2025-09-19 01:31:46.086257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import db

# revision identifiers, used by Alembic.
revision: str = '9a92ce0b5c2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('chat_type', sa.Enum('CHAT', 'GROUP', 'CHANNEL', 'PRIVATE', 'OTHER', name='chattype'), nullable=False),
    sa.Column('last_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('timezone', db.models.ZoneInfoType(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_schedule_preference',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('interval_unit', sa.Enum('HOUR', 'DAY', name='intervaltype'), nullable=False),
    sa.Column('interval_value', sa.REAL(), nullable=True),
    sa.Column('time_of_day', postgresql.ARRAY(sa.Time()), nullable=False),
    sa.Column('timezone', db.models.ZoneInfoType(length=64), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_mapping',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['source_chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['target_chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'CANCELLED', name='poststatus'), nullable=False),
    sa.Column('is_album', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('asset_url', sa.String(), nullable=True),
    sa.Column('asset_content', sa.LargeBinary(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    op.drop_table('post')
    op.drop_table('chat_mapping')
    op.drop_table('channel_schedule_preference')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
