"""added source chat to post

Revision ID: ea77eeabcebc
Revises: bbb49ecc0144
Create Date: 2025-09-10 00:32:59.214816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea77eeabcebc'
down_revision: Union[str, Sequence[str], None] = 'bbb49ecc0144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('source_chat_id', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('source_message_id', sa.Integer(), nullable=False))
    op.alter_column('post', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('post', 'source_message_id')
    op.drop_column('post', 'source_chat_id')
    # ### end Alembic commands ###
